tasks:
  - init: npm install
    command: npm install -g npm && npm install -g @angular/cli && npm install && npm update && npm audit fix && ng config -g cli.warnings.versionMismatch false && ng serve --disableHostCheck

vscode:
    extensions:
      - johnpapa.angular-essentials@0.6.3:kn6MdE8GXp3Nplq14ISQWg==
      - Mikael.Angular-BeastCode@8.1.2:mhd8UtJbsGDazjdWNkLewQ==
      - johnpapa.Angular2@8.2.0:71cwhvciDfgwVNiG3yCydw==
      - thekalinga.bootstrap4-vscode@6.1.0:duaQhthWtxWBzXAGe+5GKQ==
      - christian-kohler.path-intellisense@1.4.2:QnOrf5fk6KiVaQs4cNEP+w==
